### ISSUE TITLE
Empty env.d.ts

### ISSUE THREAD

**Issue by sarasamuel** [chihab/ngx-env#15]
I have defined my environment variables in a .env file in the root of my project, and when I run 'ng add @ngx-env/builder,' an env.d.ts file gets created in the src folder.  However, that file contains only an empty template. Is the env.d.ts supposed to be automatically populated with the variables defined in the .env file?

**Comment by chihab** [comment]
To access your environment variables you should use `process.env` object.
The `.env.d.ts` is here only so that the compiler doesn't complain when you access `process.env.NG_APP_SOME_VAR` in your TypeScript code.

I added some notes on the README section here https://github.com/chihab/ngx-env#good-practices, let me know if it not clear.
