### ISSUE TITLE
Specify path to .env file(s)

### ISSUE THREAD

**Issue by chihab** [chihab/ngx-env#43]
@otonielguajardo PR https://github.com/chihab/ngx-env/pull/42 follow up

> [dotenv supports specifying the path of the .env file](https://github.com/motdotla/dotenv#path), this PR tries to acomplish the same.
> 
> It would be awesome for proyects with structures like this:
> ![Screenshot 2023-05-27 at 1 46 21 a m](https://github.com/chihab/ngx-env/assets/23427095/e9da81e4-f1af-48e3-90e0-17c565bf131b)
> 

The only potential confustion is that we specify the .env file but we might have other files like .env.dev or .env.local that are also parsed when present.
I wonder if it wouldn't be better to set path as the folder containing the .env files rather than the file itself. WDYT?

```
            "ngxEnv": {
              "prefix": "NGX_",
              "path": ".." // could be relative or absolute
            },
```

There also another use case in monorepo setup on which we'd want have a root .env file and each project in the workspace might have their .env files that override the properties from the parent.
```
cvnl-map
  apps/
      frontend1
          .env
       frontend2
          .env
.env
```

In that case the `base` config of frontend1 and frontend2 would target the root .env
```
            "ngxEnv": {
              "prefix": "NGX_",
              "path": "../../" 
            },
```
the plugin would load all the .env files from the root down to the project one(s), the latter can override keys from the former.

**Comment by otonielguajardo** [comment]
Thank you for taking the time to review this proposal.

About ​​pointing to a directory instead of a file, I thought [this piece of code would take care of that](https://github.com/chihab/ngx-env/blob/7c5ee46fc27e839083b7c961c530da24ecb7830f/packages/builder/src/builders/plugin.ts#L19-L27). Specifying a path instead of a file makes sense to me, but **I would vote to point the main .env file relative path as dotenv does**:

![Screenshot 2023-05-28 at 10 53 11 a m](https://github.com/chihab/ngx-env/assets/23427095/ac83c692-205f-4b76-827a-1c09b111531a)

And clarifying in the documentation that all other .env files next to the main file would also be taken into account.

**Comment by chihab** [comment]
We could actually support both,: construct the dotenv paths depending on whether the path is a folder or a .env file.
Let's make that first option you've suggested happen then we can move forward.
